version: '1.0'

services:
  redis-server:
    container_name: redis-server
    image: redis:7.2
    ports:
      - 6380:6379

  geus-chat:
    container_name: geus-chat
    # image with version tag
    # ex) image: akdfkeks/geus-chat:1.0.0
    image: akdfkeks/geus-chat:0.0.1
    # command for start-up (default: yarn run start:dev)
    command: yarn run start:dev
    depends_on:
      - redis-server
    ports:
      - 3001:3000
    env_file:
      # env file name
      - .env
